function [BW,maskedImage] = background_seg(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 14-Dec-2021
%----------------------------------------------------

% Threshold image - global threshold
BW = imbinarize(X);

% Close mask with disk
radius = 45;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Invert mask
BW = imcomplement(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

